extends Object
class_name RomConstants

const RAM_SIZES : PackedInt32Array = [
	0,
	0,
	8000,
	32000,
	128000,
	64000
]

const ROM_TYPES : Array[StringName] = [
	"BASIC",
	"MBC1",
	"MBC1 + RAM",
	"MBC1 + RAM + BATTERY",
	"0x04 UNKNOWN",
	"MBC2",
	"MBC2 + BATTERY",
	"0x07 UNKNOWN",
	"ROM + RAM 1",
	"ROM + RAM + BATTERY 1",
	"0x0A UNKNOWN",
	"MMM01",
	"MMM01 + RAM",
	"MMM01 + RAM + BATTERY",
	"0x0E UNKNOWN",
	"MBC3 + TIMER + BATTERY",
	"MBC3 + TIMER + RAM + BATTERY 2",
	"MBC3",
	"MBC3 + RAM 2",
	"MBC3 + RAM + BATTERY 2",
	"0x14 UNKNOWN",
	"0x15 UNKNOWN",
	"0x16 UNKNOWN",
	"0x17 UNKNOWN",
	"0x18 UNKNOWN",
	"MBC5",
	"MBC5 + RAM",
	"MBC5 + RAM + BATTERY",
	"MBC5 + RUMBLE",
	"MBC5 + RUMBLE + RAM",
	"MBC5 + RUMBLE + RAM + BATTERY",
	"0x1F UNKNOWN",
	"MBC6",
	"0x21 UNKNOWN",
	"MBC7 + SENSOR + RUMBLE + RAM + BATTERY"
]

const LICENSE_CODES : Array[StringName] = [
	"None",
	"Nintendo R&D 1",
	"None",
	"None",
	"None",
	"None",
	"None",
	"None",
	"Capcom",
	"None",
	"None",
	"None",
	"None",
	"Electronic Arts",
	"None",
	"None",
	"None",
	"None",
	"Hudson Soft",
	"B-AI",
	"KSS",
	"None",
	"Planning Office WADA",
	"None",
	"PCM Complete",
	"San-X",
	"None",
	"None",
	"Kemco",
	"SETA Corporation",
	"Viacom",
	"Nintendo",
	"Bandai",
	"Ocean Software / Acclaim Entertainment",
	"Konami",
	"HectorSoft",
	"None",
	"Taito",
	"Hudson Soft",
	"Banpresto",
	"None",
	"Ubi Soft",
	"Atlus",
	"None",
	"Malibu Interactive",
	"None",
	"Angel",
	"Bullet-Proof Software",
	"None",
	"Irem",
	"Absolute",
	"Acclam Entertainment",
	"Activision",
	"Sammy USA Corporation",
	"Konami",
	"Hi Tech Expressions",
	"LJN",
	"Matchbox",
	"Mattel",
	"Milton Bradley Company",
	"Titus Interactive",
	"Virgin Games Ltd.",
	"None",
	"None",
	"Lucasfilm Games",
	"None",
	"None",
	"Ocean Software",
	"EA (Electronic Arts)",
	"Infogrames",
	"Interplay Entertainment",
	"Broderbund",
	"Sculptured Software",
	"None",
	"The Sales Curve Limited",
	"None",
	"None",
	"THQ",
	"Accolade",
	"Misawa Entertainment",
	"None",
	"None",
	"Iozc",
	"None",
	"None",
	"Tokuma Shoten",
	"Tsukuda Original",
	"None",
	"None",
	"None",
	"Chunsoft Co.",
	"Video System",
	"Ocean Software / Acclaim Entertainment",
	"None",
	"Varie",
	"Yonezawa's Pal",
	"Kaneko",
	"None",
	"Pack-In-Video",
]
